# Adrian Vrouwenvelder
# November 2022
# April 2023
pid:
  gains:
    default:
      P: 8.170
      I: 0
      D: 0

boat:
  # How long rudder stop to stop using automation
  rudder_hardover_time_s: 4 # From centered to stop
  # Degrees per second
  boat_turn_rate_dps: 10.0
  # Sampling interval in ms
  sampling_interval: 100

  course_tolerance_deg: 0.1

mpu9250:
  # The following were measured on 08-Apr-2023 by mpu9360-calibration.py, which uses jmdev's MPU library
  gyro: # Gyro units = degrees per second
    bias: [ -2.194, 0.670, 0.047]
    moving_average_window_size: 5
  accel: # Accelerometer units = Gs
    bias: [-0.007, 0.008, .033]
    moving_average_window_size: 5
  temp: # Celsius
    bias: 0
    moving_average_window_size: 5
  mag: # Magnetometer units = microTeslas
    # FYI Chip factory calibration = [1.19921875, 1.19921875, 1.15234375]
    calib: [ 1.19921875, 1.19921875, 1.15234375 ]
    bias: [ 33.30, 0.13, 10.6 ]
    scale: [ 0.731, 0.722, 4.000 ]
    moving_average_window_size: 100