# Adrian Vrouwenvelder
# November 2022
# April 2023

# Tuning Rule of Thumb (Ziegler-Nichols)
# 1. Set all gains to zero.
# 2. Increase the P gain until the response to a disturbance is steady oscillation.
# 3. Increase the D gain until the the oscillations go away (i.e. it's critically damped).
# 4. Repeat steps 2 and 3 until increasing the D gain does not stop the oscillations.
# 5. Set P and D to the last stable values.
# 6. Increase the I gain until it brings you to the setpoint with the number of oscillations desired (normally zero but a quicker response can be had if you don't mind a couple oscillations of overshoot)

log_level: 2

pid:
  log_level: 3
  gains:
    default:
#      P: 8.170 - 9.8s
#      P: 10 - 9.0s
#      P: 15 - 5.6s
#      P: 16 - 5.1s
#      P: 16.5 - 4.2s
#      P: 16.6 - 4.2s
#      P: 16.75 - 4.2s
#      P: 16.8 - 4.1s
#      P: 16.9 - 4.6s
#      P: 17 - 4.4s
#      P: 18.5 - 6.9s
#      P: 20 - 7.6s
      # 40
      P: 17
#      P: 30 - 10s
#      P: 40 - 14s
#      P: 40 - 14s
      I: 0
      D: 0

brain:
  log_level: 3

boat:
  log_level: 3
  # How long rudder takes to go from stop to stop
  rudder_hardover_time_s: 4 # From centered to stop
  # Degrees per second
  boat_turn_rate_dps: 10.0
  # Sampling interval in ms - how frequently the brain may change the rudder motor depending on commanded vs actual rudder
  sampling_interval: 100
  # Rudder tolerance = how far off can rudder be the desired angle before actuator corrects
  rudder_tolerance: 0.01
  # Course tolerance = How far off can course be before AP action is taken
  course_tolerance_deg: 0.2

arduino:
  log_level: 3

mpu9250:
  log_level: 2
  # The following were measured on 08-Apr-2023 by mpu9250-calibration.py, which uses jmdev's MPU library
  gyro: # Gyro units = degrees per second
    bias: [ -2.194, 0.670, 0.047]
    moving_average_window_size: 5
  accel: # Accelerometer units = Gs
    bias: [-0.007, 0.008, .033]
    moving_average_window_size: 5
  temp: # Celsius
    bias: 0
    moving_average_window_size: 5
  mag: # Magnetometer units = microTeslas
    # FYI Chip factory calibration = [1.19921875, 1.19921875, 1.15234375]
    calib: [ 1.19921875, 1.19921875, 1.15234375 ]
    bias: [ 33.30, 0.13, 10.6 ]
    scale: [ 0.731, 0.722, 4.000 ]
    moving_average_window_size: 100
