# Adrian Vrouwenvelder
# October 2023

boat_max_turn_rate_dps: 10.0
metric_tolerance: 0.01
course_tolerance_deg: 0.5

# PID Tuning Rule of Thumb (Ziegler-Nichols)
# 1. Set all gains to zero.
# 2. Increase the P gain until the response to a disturbance is steady oscillation.
# 3. Increase the D gain until the the oscillations go away (i.e. it's critically damped).
# 4. Repeat steps 2 and 3 until increasing the D gain does not stop the oscillations.
# 5. Set P and D to the last stable values.
# 6. Increase the I gain until it brings you to the setpoint with the number of oscillations desired (normally zero but
#    a quicker response can be had if you don't mind a couple oscillations of overshoot)
pid_gains:
#   calm: [0.0500, 0.0001, 0.0000]  # Pretty good.
#   calm: [0.2, 0.0105, 0.0000]  # Overshoots
#    calm: [0.2, 0.0, 0.100]  # Overshoots but corrects quickly
   calm: [0.2, 0.0, 0.200]  # Overshoots a little but corrects very quickly

# Inertial Measurement Unit (IMU)
imu_sampling_interval_ms: 100

# IMU Gyro
imu_gyro_bias: [ -2.194, 0.670, 0.047] # Gyro units = degrees per second
imu_gyro_moving_average_window_size: 5

# IMU Accelerometer
imu_accel_bias: [-0.007, 0.008, .033]
imu_accel_moving_average_window_size: 5

# IMU Temperature
imu_temperature_bias: 0 # Celsius
imu_temperature_moving_average_window_size: 5

# IMU Magnetometer (units = microTeslas)
imu_magnetometer_calib: [ 1.19921875, 1.19921875, 1.15234375 ] # Factory calibration = [1.19921875, 1.19921875, 1.15234375]
imu_magnetometer_bias: [ 33.30, 0.13, 10.6 ]
imu_magnetometer_scale: [ 0.731, 0.722, 4.000 ]
imu_magnetometer_moving_average_window_size: 100

# Rudder interface settings
rudder_echo_status: 1
rudder_reporting_interval_ms: 100
rudder_starboard_limit: 0973
rudder_port_limit: 0050
rudder_hard_over_time_ms: 4000 # From centered to stop - for simulations
